# platinfo config
plat:
    name: plat-test

# systeminfo config
system:
    name: system-test
    # mode: debug/release
    mode: debug
    # api/cron
    type: api|cron

# logger config
logger:
    # panic/fatal/error/info/debug/trace  all contains all level
    level: all
    # stdout/file
    out: stdout

# http server config
httpserver:
    cors:
        header:
        - 'Access-Control-Allow-Origin': 'http://10.12.194.50:8081' 
        - 'Access-Control-Allow-Credentials': 'true'
        - 'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,PATCH,OPTIONS'
        - 'Access-Control-Allow-Headers': '__jwt__'
        - 'Access-Control-Expose-Headers': '__jwt__'
        enable: false
    address: :8080
    status: start

# cron server config
cronserver:
    status: start

